#!/bin/sh

#  Copyright (C) 2025 by Abhirath Koushik

#  Redistribution, modification or use of this software in source or binary
#  forms is permitted as long as the files maintain this copyright. Users are
#  permitted to modify this and use it to learn about the field of embedded
#  software. Abhirath Koushik and the University of Colorado are not liable for
#  any misuse of this material.

#  @file    S98lddmodules.sh
#  @brief   This script is used to load and unload the ldd modules.

#  @author  Abhirath Koushik
#  @date    03-09-2025

case "$1" in
    start)
        echo "Loading LDD modules..."
        
        # Load scull driver
        scull_load.sh

        # Load faulty driver
        module_load.sh faulty

        # Load hello module using modprobe
        modprobe hello
        ;;
    stop)

        echo "Unloading LDD modules..."

        # Unload hello module
        rmmod hello || echo "Failed to remove hello module"

        # Unload faulty driver
        module_unload.sh faulty

        # Unload scull driver
        scull_unload.sh
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
